# Generated by Django 5.2.6 on 2025-10-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='cleaning_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='service_fee_percent',
            field=models.PositiveIntegerField(default=10, help_text='Service fee as a percentage (e.g., 10 for 10%)'),
        ),
    ]
