# Generated by Django 5.2.6 on 2025-10-12 23:15
# In property/migrations/0003_add_fulltext_search.py

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0002_property_cleaning_fee_property_service_fee_percent"),
    ]

    operations = [
        # These enable advanced search capabilities in PostgreSQL
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS pg_trgm;"),
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS unaccent;"),
    ]
