# Generated by Django 5.2.6 on 2025-10-13 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_add_search_vector'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='property',
            name='property_search_idx',
        ),
    ]
